version: 2
jobs:
  build:
    working_directory: /go/src/github.com/a4t/misudo
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout
      - run: make deps
      - run: make cross-build
      - save_cache:
          key: build-{{ epoch }}
          paths:
            - /go/src/github.com/a4t/misudo/dist

  release:
    working_directory: /go/src/github.com/a4t/misudo
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-
      - run: make release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}/
